### ISSUE TITLE
Always authorizing all client scopes regardless of the scopes requested when request scopes are enabled

### ISSUE THREAD

**Issue by tarsislima** [denniseilander/laravel-passport-scopes-restriction#1]
Hello, 

This lib has been very useful to me as it allows limiting client scopes. However, it has a limitation of always authorizing all scopes regardless of the scopes requested in the payload when creating the token.

I have the following scenario ,  

ClientX  has  serviceA , ServiceB , and ServiceC scopes saved in database to act as allowed client scopes rather than authorized scopes.
When i request a token i want pass an array of only needed scopes inside allowed list to apply in current token generated.

when call auth/token with [ 'ServiceB'] at 'scope' param at payload ( that is a valid scope to this specific client)  then this token result needs create only this scope inside token. 

Because this snippet code always all scopes are assigned to token ignoring the 'scope' atribute at payload.

` $scopes = array_intersect($scopes, $allowedScopes);`

**Comment by denniseilander** [comment]
Hi @tarsislima, 

Thanks for using this package!
I took a look and you're right, the problem is within the `$scopes = array_unique(array_merge($allowedScopes, $scopes), SORT_REGULAR);`. It always merge the scopes in the request with the allowed scopes, so you end up having all the allowed scopes in the database for that access_token.

I'll push a fix!
